---
title: 'Generació de dades 2: escenari 50%'
author: "Max Ranz de la Iglesia"
date: "2026-05-14"
output: html_document
---

# Generació de les dades: 50% variables rellevants + correlació aleatòria

```{r}
# Llibreries
library(logistf)
library(MASS)
library(dplyr)
library(tidyr)
library(ggplot2)
library(caret)

set.seed(123)

# PARÀMETRES

num_vars <- 100
num_sig <- num_vars/2

num_vars2 <- num_vars/2
num_sig2 <- num_vars2/2

iters <- 100
iters_boot <- iters*2

# Afegim "random"
correlation_levels <- c(0, 0.1, 0.3,"random")

# combinacions possibles
comb <- expand.grid(
  N = c(500, 1000),
  pi = c(0.1, 0.3),
  correlation = correlation_levels
)

# coeficients de variables rellevants
beta <- rep(0.1, num_sig)

```


## FUNCIÓ PER GENERAR X AMB CORRELACIÓ

```{r}
generate_data <- function(N, num_vars, correlation){

  corr_val <- as.character(correlation)

  # CAS: correlació aleatòria
  if(corr_val == "random"){

    loadings <- runif(num_vars,
                      min = 0,
                      max = sqrt(0.3))

    corr_matrix <- outer(loadings, loadings)

    diag(corr_matrix) <- 1

  } else {

    corr_val <- as.numeric(corr_val)

    # CAS: independència
    if(corr_val == 0){

      corr_matrix <- diag(num_vars)

    } else {

      # correlació constant
      corr_matrix <- matrix(corr_val,
                            nrow = num_vars,
                            ncol = num_vars)

      diag(corr_matrix) <- 1
    }
  }

  X <- mvrnorm(
    n = N,
    mu = rep(0, num_vars),
    Sigma = corr_matrix,
    tol = 1e-3
  )

  colnames(X) <- paste0("X", 1:num_vars)

  return(X)
}

# Generació de dades principal   

X <- list()
Y <- list()

for(i in 1:nrow(comb)){

  N <- comb$N[i]
  pi <- comb$pi[i]
  correlation <- comb$correlation[i]

  X[[i]] <- list()
  Y[[i]] <- list()

  for(j in 1:iters){

    # Generar predictors
    X[[i]][[j]] <- generate_data(
      N,
      num_vars,
      correlation
    )

    # Model logístic:
    # primeres 50 variables rellevants

    log_odds <- X[[i]][[j]][,1:num_sig] %*% beta

    # Ajust prevalença
    offset <- log(pi/(1-pi)) - mean(log_odds)

    log_odds <- log_odds + offset

    prob <- 1/(1 + exp(-log_odds))

    # resposta binària
    Y[[i]][[j]] <- rbinom(N, 1, prob)
  }
}


# Dades BOOTSTRAP


X2 <- list()
Y2 <- list()

for(i in 1:nrow(comb)){

  N <- comb$N[i]
  pi <- comb$pi[i]
  correlation <- comb$correlation[i]

  X2[[i]] <- list()
  Y2[[i]] <- list()

  for(j in 1:iters_boot){

    X2[[i]][[j]] <- generate_data(
      N,
      num_vars2,
      correlation
    )

    log_odds <- X2[[i]][[j]][,1:num_sig2] %*%
      beta[1:num_sig2]

    offset <- log(pi/(1-pi)) - mean(log_odds)

    log_odds <- log_odds + offset

    prob <- 1/(1 + exp(-log_odds))

    Y2[[i]][[j]] <- rbinom(N, 1, prob)
  }
}


# Mètriques


metriques <- function(vars_seleccionades,
                      p = 0.5,
                      nv){

  num_sig <- nv/2

  real_labels <- c(
    rep(1, num_sig),
    rep(0, nv - num_sig)
  )

  pred_labels <- rep(0, nv)

  pred_labels[vars_seleccionades] <- 1

  cm <- confusionMatrix(
    as.factor(pred_labels),
    as.factor(real_labels),
    positive = "1"
  )

  TP <- cm$table[2,2]
  FP <- cm$table[2,1]
  FN <- cm$table[1,2]
  TN <- cm$table[1,1]

  sensibilitat <- ifelse((TP+FN)==0,
                         NA,
                         TP/(TP+FN))

  especificitat <- ifelse((TN+FP)==0,
                          NA,
                          TN/(TN+FP))

  VPP <- ifelse((TP+FP)==0,
                NA,
                TP/(TP+FP))

  VPN <- ifelse((TN+FN)==0,
                NA,
                TN/(TN+FN))

  accuracy <- (TP+TN)/(TP+TN+FP+FN)

  net_benefit <- (TP/nv) -
    (FP/nv)*(p/(1-p))

  return(
    c(
      sensibilitat = sensibilitat,
      especificitat = especificitat,
      VPP = VPP,
      VPN = VPN,
      accuracy = accuracy,
      net_benefit = net_benefit
    )
  )
}



```

## Comprovació
```{r}


for(i in 1:length(X)) {

  cat("\n-----------------------------\n")
  cat("Escenari:", i, "\n")

  X_comb <- do.call(rbind, X[[i]])
  Y_comb <- unlist(Y[[i]])

  cat("Dimensions X:", dim(X_comb), "\n")

  cat("Proporció Y:\n")
  print(prop.table(table(Y_comb)))

  cor_matrix <- cor(X_comb)

  cor_mitjana <- mean(
    cor_matrix[upper.tri(cor_matrix)]
  )

  cat("Correlació mitjana observada:",
      round(cor_mitjana,4), "\n")

  cat("Correlació esperada:",
      ifelse(as.character(comb$correlation[i])=="random",
             "U(0,0.3)",
             as.character(comb$correlation[i])),
      "\n")
}

```

```{r}
save(comb,X,Y,X2,Y2,num_vars,num_sig, num_vars2, num_sig2,beta, iters, iters_boot,metriques, file = "dades_escenari_50_corrAleat.RData")
```

