---
title: "Model: escenari 50%"
autho: "Max Ranz"
output: html_document
date: "2026-03-16"
---

 # Generació de les dades: 50% de dades rellevants
```{r}

# paquets d'interès
library(logistf)
library(MASS)
library(dplyr)
library(tidyr)
library(ggplot2)
set.seed(123) #llavor per obtenir els mateixos resultats al simular

# PARÀMETRES

num_vars <- 100          # total variables
num_sig <- num_vars / 2  # 50 variables rellevants
num_vars2 <- num_vars/2
num_sig2 <- num_vars2/2

iters <- 100
iters_boot <- iters*2

correlation_levels <- c(0, 0.1, 0.3)

# combinacions
comb <- expand.grid(
  N = c(1000, 5000),
  pi = c(0.1, 0.3),
  correlation = correlation_levels
)

# coeficients de variables rellevants
beta <- rep(0.1, num_sig)

# FUNCIÓ PER GENERAR X: afegint correlacions entre les variables
generate_data <- function(N, num_vars, correlation){
  corr_matrix <- matrix(correlation, nrow=num_vars, ncol=num_vars)
  diag(corr_matrix) <- 1
  X <- mvrnorm(n=N, mu=rep(0,num_vars), Sigma=corr_matrix)
  colnames(X) <- paste0("X",1:num_vars)
  return(X)
}

# GENERACIÓ DE DADES PRINCIPAL

X <- list()
Y <- list()

for(i in 1:nrow(comb)){
  
  N <- comb$N[i]
  pi <- comb$pi[i]
  correlation <- comb$correlation[i]
  
  X[[i]] <- list()
  Y[[i]] <- list()
  
  for(j in 1:iters){
    
    X[[i]][[j]] <- generate_data(N, num_vars, correlation)
    
    # model amb 50 variables rellevants
    log_odds <- X[[i]][[j]][,1:num_sig] %*% beta
    
    # offset per prevalença
    offset <- log(pi/(1-pi)) - mean(log_odds)
    log_odds <- log_odds + offset
    
    prob <- 1/(1+exp(-log_odds))
    
    Y[[i]][[j]] <- rbinom(N,1,prob)
  }
}


# DADES BOOTSTRAP 

X2 <- list()
Y2 <- list()

for(i in 1:nrow(comb)){
  
  N <- comb$N[i]
  pi <- comb$pi[i]
  correlation <- comb$correlation[i]
  
  X2[[i]] <- list()
  Y2[[i]] <- list()
  
  for(j in 1:iters_boot){
    
    X2[[i]][[j]] <- generate_data(N, num_vars2, correlation)
    
    log_odds <- X2[[i]][[j]][,1:num_sig2] %*% beta[1:num_sig2]
    offset <- log(pi/(1-pi)) - mean(log_odds)
    log_odds <- log_odds + offset
    
    prob <- 1/(1+exp(-log_odds))
    Y2[[i]][[j]] <- rbinom(N,1,prob)
  }
}
```

```{r}
# FUNCIÓ AMB LES MÈTRIQUES MÉS RELLEVANTS
metriques <- function(vars_seleccionades, p=0.5, nv) {
  num_sig <- nv/2
  real_labels <- c(rep(1, num_sig), rep(0, nv - num_sig))
  pred_labels <- rep(0, nv)
  pred_labels[vars_seleccionades] <- 1
  
  cm <- confusionMatrix(as.factor(pred_labels), as.factor(real_labels), positive="1")
  TP <- cm$table[2,2]
  FP <- cm$table[2,1]
  FN <- cm$table[1,2]
  TN <- cm$table[1,1]
  
  sensibilitat <- ifelse((TP+FN)==0, NA, TP/(TP+FN))
  especificitat <- ifelse((TN+FP)==0, NA, TN/(TN+FP))
  VPP <- ifelse((TP+FP)==0, NA, TP/(TP+FP))
  VPN <- ifelse((TN+FN)==0, NA, TN/(TN+FN))
  accuracy <- (TP+TN)/(TP+TN+FP+FN)
  net_benefit <- (TP/nv) - (FP/nv)*(p/(1-p))
  
  return(c(sensibilitat=sensibilitat,
           especificitat=especificitat,
           VPP=VPP,
           VPN=VPN,
           accuracy=accuracy,
           net_benefit=net_benefit))
}
```

```{r}
# COMPROVACIÓ (mirar si s'han generat bé les dades)

num_cols_summary <- 5

for(i in seq_along(X)){
  
  cat("\n---------------------------\n")
  cat("Combinació i =", i, "\n")
  
  X_comb <- do.call(rbind, X[[i]])
  Y_comb <- unlist(Y[[i]])
  
  cat("Dimensions X:", dim(X_comb), "\n")
  
  # Primeres variables
  X_first <- as.data.frame(X_comb[,1:num_cols_summary])
  cat("\nResum primeres", num_cols_summary, "variables:\n")
  print(summary(X_first))
  
  X_first$Y <- as.factor(Y_comb)
  X_long <- pivot_longer(X_first, cols=1:num_cols_summary,
                         names_to="Variable", values_to="Valor")
  
  p <- ggplot(X_long, aes(x=Variable, y=Valor, fill=Y)) +
    geom_boxplot(outlier.size=0.5) +
    labs(title=paste("Boxplot primeres", num_cols_summary, "variables (combinació", i, ")")) +
    theme_minimal()
  print(p)
}
```
## Comprovar que s'obtenen les correlacions i prevalences desitjades.
```{r}
for (i in 1:length(X)) {
  
  cat("\n-----------------------------\n")
  cat("Escenari:", i, "\n")
  
  X_comb <- do.call(rbind, X[[i]])
  Y_comb <- unlist(Y[[i]])
  
  cat("Dimensions X:", dim(X_comb), "\n")
  
  cat("Proporció Y:\n")
  print(prop.table(table(Y_comb)))
  
  # Matriu de correlacions
  cor_matrix <- cor(X_comb)
  
  # Mitjana fora diagonal
  cor_mitjana <- mean(cor_matrix[upper.tri(cor_matrix)])
  
  cat("Correlació mitjana observada:",
      round(cor_mitjana, 4), "\n")
  
  cat("Correlació esperada:",
      comb$correlation[i], "\n")
}
```

```{r}
save(comb, X, Y, X2, Y2,num_vars, num_sig, num_vars2, num_sig2, beta, iters, iters_boot,metriques,
     file = "dades_escenari_50.RData")
```